### ISSUE TITLE
Ringbuffer is not a Template

### ISSUE THREAD

**Issue by Namenlossss** [franckmarini/KnxDevice#3]
When I try to compile the any project with this library (including the example projects) on the Arduino ide 1.6.9 for the Arduino due I get the following error:

```
In file included from C:\Program Files (x86)\Arduino\libraries\KnxDevice-master/KnxDevice.h:30:0,
from C:\Program Files (x86)\Arduino\libraries\KnxDevice-master\examples\KnxDevice_PushButton\KnxDevice_PushButton.ino:12:

C:\Program Files (x86)\Arduino\libraries\KnxDevice-master/RingBuffer.h:38:7: error: 'RingBuffer' is not a template type

 class RingBuffer {

       ^

In file included from C:\Program Files (x86)\Arduino\libraries\KnxDevice-master\examples\KnxDevice_PushButton\KnxDevice_PushButton.ino:12:0:

C:\Program Files (x86)\Arduino\libraries\KnxDevice-master/KnxDevice.h:108:5: error: 'RingBuffer' is not a template

     RingBuffer<type_tx_action, ACTIONS_QUEUE_SIZE> _txActionList; // Queue of transmit actions to be performed

     ^
```

I have tried to redownload the latest version of the library, reinstalliing the Arduino IDE and switching from native to programming USB port.
I have not modified the library in any way.
![error](https://cloud.githubusercontent.com/assets/17949819/15986348/68dd9e84-3006-11e6-9b4b-9975f289899d.png)
Screenshot of the error message.

**Comment by franckmarini** [comment]
Hi Namenlossss,
I've not managed to reproduce the issue using IDE 1.6.9 and Arduino Due board. Is this issue still present ?

**Comment by Namenlossss** [comment]
Found the problem. a new version of the Arduino  Board file was used. No problem with the library, sorry.

**Comment by franckmarini** [comment]
Thanks Namenlossss for your feedback.
